### PR TITLE
Add program_raw_data saveframe AND change atom names (HBX  to HBx, ...)

### PR DESCRIPTION
**Pull request by rhfogh**
This pull request bundles two changes (sorry). 

1_ add _programnamespace_raw_data saveframe, a standard saveframe in program-specific namespace,
to save input file contents and unstructured data.
1. Change atom names:
   a. Accept only upper case atom names as matches to molecule
   b., Change non-stereo-assignment wildcards from X/Y (upper case) to x/y (lower case)
   c. Tighten rules for accepted wildcard expressions.

### CODE REVIEW

**Comment by rhfogh** [comment]
It has been pointed out - correctly - that the raw_data saveframe is not really a change to NEF, since it regards only the freely changeable program-specific data. It is added as a recommendation 1) to deposit additional data in this way, if nothing more precise has been set up, 2) to use this standard form that is easier for people to read.

**Comment by perzeus** [comment]
I would argue that it is indeed a change, as new tags have to be defined to be able to insert such data in a way consistent with the format definition.

Just my two cents…

Pedro


--
Pedro R. Romero
Director
Biological Magnetic Resonance Data Bank
Department of Biochemistry
University of Wisconsin - Madison
B1118a Biochemistry
420 Henry Mall
Madison, WI 53706
email: promero@wisc.edu<mailto:promero@wisc.edu>
Voice: 608-265-5741
FAX: 608-262-3759

On Oct 3, 2016, at 6:55 AM, rhfogh <notifications@github.com<mailto:notifications@github.com>> wrote:


It has been pointed out - correctly - that the raw_data saveframe is not really a change to NEF, since it regards only the freely changeable program-specific data. It is added as a recommendation 1) to deposit additional data in this way, if nothing more precise has been set up, 2) to use this standard form that is easier for people to read.

**Comment by elulrich** [comment]
Regarding the "programspecific_raw_data", if my comment does not make sense please excuse me. But I thought the proposal was to create a generic save frame that would be a place holder for raw data (ASCII) from the program that generated the NEF file. Not that each software package would create a unique save frame for the raw data that is generated. If the generic save frame is the idea then I would think this is an addition (change) to the NEF dictionary and specification.

**Comment by elulrich** [comment]
Regarding X/Y versus x/y, I am not sure of the rationale for using x/y. I am not aware of software that is currently sensitive to case sensitive atom nomenclature.

**Comment by elulrich** [comment]
In these early stages of the development of NEF and the NEF atom nomenclature specifications, having the restraint data written out in the software's native format for comparison with the same restraint data in the NEF format will allow the NEF format to be evaluated for completeness and accuracy. In the limited number of files where we have been able to make this comparison, we have found a few potential issues.

**Comment by rhfogh** [comment]
On  program_specific data, my understanding is the same as yours. The choice was then between a saveframe in nef-space with a field giving the program prefix for the program that provided the data. We went instead for the alternative proposal of having the saveframe in program-specific space (without the program-prefix tag), and specifying a standard format for it - the reason being that we were talking about program-specific data after all. The two alternatives are very similar, to my mind. Do you think it would be materially easier for you if we went for the nef-space solution?

**Comment by rhfogh** [comment]
The rationale for x/y (rather than X/Y) would be that 1) we are anyway going for a case-sensitive standard, so that e.g. 'HA' but *not 'ha' match an atom in the molecule; 2) It is easier to detect the wildcards if you do not have to distinguish them from atom names with 'X' (like 'HXT'); 3) The wildcards stand out more when they are in a different case.

**Pull request merged**
