### PR TITLE
Add _nef_sequence.ordinal

### PR DESCRIPTION
**Pull request by rhfogh**
Add ordinal column to _nef_sequence loop, to reflect the (significant) order of lines in the loop.

### CODE REVIEW

**Comment by rhfogh** [comment]
The point has been raised whether this should not have been 'index_id' rather than 'ordinal'.

I put it as 'ordinal', since, unlike other cases, this tag is actually meant to reflect a significant ordering, not to simply serve as pro-forma ID. But if our knowledgeable database people have a better alternative, I think we shold follow their advice.

**Comment by elulrich** [comment]
If the value is intended to specify and maintain a specific ordering of the rows as is the case for the listing of authors on a manuscript then 'ordinal' seems appropriate.

**Comment by wvranken** [comment]
I think 'index_id' is overkill, just stick with 'id' or 'index' - both of which are more suitable as a term than 'ordinal' in my view

**Comment by gvuister** [comment]
I agree with Wim: index_id is a tautology and we should use index (in computing sense:  a set of items each of which specifies one of the records of a file and contains information about its address). 
I think it is good to have, as any processing routine can always establish the order of the records from it.

**Comment by gvuister** [comment]
I agree with Wim: index_id is a tautology and we should use index (in computing sense:  a set of items each of which specifies one of the records of a file and contains information about its address). 
I think it is good to have, as any processing routine can always establish the order of the records from it.

**Comment by rhfogh** [comment]
After discussion it seems that this tag should be 'index'. The pull request will be superseded, and is reopened for technical reasons only. See pull request 'rename_to_index' for discussion

**Pull request merged**
