### PR TITLE
New residue variants

### PR DESCRIPTION
**Pull request by rhfogh**
Change specification of residue variants, from RCSB system
to specifying atoms added/removed relative to base form.
Added explicit lists of supported standard residues and nucleotides,
together with their atoms and wildcard expressions and the supported residue variants

### CODE REVIEW

**Comment by elulrich** [comment]
With regard to residue variants, I am not sure of the rationale to go with 'added/removed' atom specifications. I tend to encourage using an existing standard if available and it works. At least the RCSB system provides a well defined topology file for the variant residues.
Eldon

**Comment by rhfogh** [comment]
We did indeed start out using the RCSB system, because it is an existing standard, as you say. We changed our minds because 1) the RCSB system only covered standard amino acids, and could not easily be extended to ther nucleutides or to other variants; 2) because it was very complex in use, 3) this in part because the RCSB code included information that was already given in other columns of the _nef_sequence loop, like the residue_name, the N-terminal, C-terminal, or non-terminal position, and the distinction between L and D amino acids, 4) it is built as an added-and-subtracted-atom system like the new one, but with the default state fully protonated rather than pH 7.

Would it help if we made an official table, giving the mapping from the new variant codes to the RCSB codes in all cases where the latter are defined?

**Comment by wvranken** [comment]
I can see that a new definition will make things simpler, but it's another thing to define and maintain - is the RCSB system really not practical to use?

**Comment by rhfogh** [comment]
Not very practical, no. 

To be sure, the RCSB code could be derived algorithmically from variant codes and other available information, so technically they are interchangeable. But the RCSB codes are limited to the 20 standard amino acids. You could extend the set of names to new variants, but there is no chance of anybody providing or maintaining the kind of detailed individual topology descriptions that the RCSB has made for the existing set (unless the RCSB volunteers?). All you would have is the name, and the obligation to parse and interpret it yourself.  If we want to be able to support properly non-standard residues or links beyond the standard sequence and disulfides, sticking to the RCSB system will give us no more support than changing to the new one..

Then the RCSB names are decidedly clunky and opaque, because they include information that is already given in the residue_name and linking. 

The variant code for disulfide-linked cysteine at pH 7 is "-HG" .

The corresponding RCSB code is one of "CYS_LSN3_DHG", "CYS_LL_DHG", and "CYS_LEO2_DHG"> for N-termnial, middle, and C-terminal variants, respectively.

**Comment by rhfogh** [comment]
Coming back, I think that there are two options that are definitely possible:

1-  We use the new system of variant codes.
2- We stay with RCSB codes for standard amino acids and do not support variant codes in any other cases.

I am not sure what a third alternative might look like - does anybody have any proposals?

**Comment by kumar-physics** [comment]
@rhfogh Will NEF consortium maintain the library of new system of variant codes with detailed topology descriptions in the future?  With my knowledge  non standard residues are not fully  supported by NEF atom nomenclature. Wild card expressions can not be expanded for non standard residues with out proper topology information.   This shows non standard residues are not fully supported in  NEF, so why don't NEF adopt to the established and maintained system for at least standard 20 amino acids(and its variants) ?

**Comment by rhfogh** [comment]
There are two problems here:

The original proposal was to use the RCSB codes, but going back over our notes these were rejected by the developers as too cryptic and cumbersome to use - once they realised that they entailed. The information tables can be found in the main branch still.

The other problem is how to maintain a set of detailed topology descriptions for all the known residues and their variants. And so far the only body willing to do anything like that is the RCSB - no one else has the resources. So unless someone volunteers we shall have to rely on the RCSB topology descriptions as the only game in town - both for basic forms of chemical compounds, and for residue variants (which the RCSB supports only for the 20 standard amino acids). That leaves the question whether to use the RCSB *variant codes* as well as their topology descriptions, and what to do about variants that are not supported by the RCSB.

Here the proposal is that:

1. The NEF residue_names map directly to the RCSB chemical compound names, and so we can rely on RCSB topologues.

2. For variants  we use the nef naming convention, which is both simpler and easier to extend than he RCSB convenrtion. 

3. For the existing RCSB variant codes (for those 20 amino acids), we provide a table that maps the RCSB variant codes precisely to the combination of nef residue_name, linking, and residue_variant that they correspond to. This again, allows people to rely on the RCSB topologies.

4. For variants that are not supported by the RCSB, the nef variant codes allow us to specify the relevant atoms and bonds in a manner intelligible to a chemist. This is the best that can be done - given that the agreement is to *not* make topology specification part of the format - unless somebody volunteers to write and maintain the additional topology files. Programs will not be obliged to interpret non-standard variant codes (any more than they are obliged to understand residue names outside the twenty standard amino acids), but the new system at least makes it possible to specify the information correctly for those programs that make the effort to interpret it. Surely that is better than saying that non-standard residues cannot be represented in NEF at all?

**Comment by wvranken** [comment]
After our further discussions I understand why you are aiming for a new system that is easier to understand and more flexible - as for the isotopes, I would here make a prominent reference in a header comment to the mmCIF chemcomp definitions however, so that it's clear what '-HG' means in terms of atom specification.

**Pull request merged**
